name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up virtualenv
        run: python -m venv .venv

      - name: Install dependencies
        run: |
          .venv/bin/pip install -U pip
          .venv/bin/pip install -e .[dev]

      - name: Run tests
        run: .venv/bin/pytest

